import { Category, FAQItem, Product, Review, StatItem } from "@/types";

export const brands = [
  "Logitech",
  "HyperX",
  "Razer",
  "Corsair",
  "SteelSeries",
  "Asus ROG",
  "MSI",
  "Redragon",
  "Xiaomi",
  "Ajazz",
  "Onikuma",
  "Aula",
  "Irok",
];

export const categories: Category[] = [
  {
    slug: "teclados",
    name: "Teclados",
    description: "Mecánicos, hot-swap y low profile para competitivo.",
    heroLabel: "Precisión por tecla",
  },
  {
    slug: "mouse",
    name: "Mouse",
    description: "Sensores de alto rendimiento y peso ultraliviano.",
    heroLabel: "Control total",
  },
  {
    slug: "mousepads",
    name: "Mousepads",
    description: "Superficies XL, speed y control para cada estilo.",
    heroLabel: "Deslizamiento perfecto",
  },
  {
    slug: "auriculares",
    name: "Auriculares",
    description: "Audio inmersivo y micrófonos nítidos para squad.",
    heroLabel: "Escuchá cada detalle",
  },
  {
    slug: "monitores",
    name: "Monitores",
    description: "Alta tasa de refresco y baja latencia real.",
    heroLabel: "Frame advantage",
  },
  {
    slug: "accesorios",
    name: "Accesorios",
    description: "Webcams, soportes y extras para tu setup.",
    heroLabel: "Tu setup completo",
  },
];

export const stats: StatItem[] = [
  { label: "Clientes felices", value: "+18.500" },
  { label: "Productos activos", value: "+420" },
  { label: "Satisfacción", value: "98,7%" },
  { label: "Envíos realizados", value: "+32.000" },
];

const toInstallments = (_price: number) => "Medios de pago disponibles";

export const products: Product[] = [
  {
    id: "p1",
    slug: "teclado-logitech-g-pro-x-tkl-lightspeed",
    name: "Teclado Logitech G Pro X TKL Lightspeed",
    brand: "Logitech",
    category: "teclados",
    price: 289999,
    previousPrice: 329999,
    stock: 8,
    installments: toInstallments(289999),
    badges: ["oferta", "destacado"],
    shortDescription: "TKL inalámbrico para esports con switches intercambiables.",
    description:
      "Diseñado para competitivo, el Pro X TKL combina respuesta ultrarrápida, conexión LIGHTSPEED y construcción premium en aluminio.",
    specs: [
      { label: "Switch", value: "GX Tactile" },
      { label: "Conectividad", value: "Wireless + USB-C" },
      { label: "Formato", value: "TKL" },
      { label: "Iluminación", value: "RGB LIGHTSYNC" },
    ],
    images: ["Vista frontal", "Vista lateral", "Detalle switches"],
    rating: 4.9,
    reviewCount: 82,
    sold: 210,
    isFeatured: true,
  },
  {
    id: "p2",
    slug: "mouse-razer-viper-v3-pro",
    name: "Mouse Razer Viper V3 Pro",
    brand: "Razer",
    category: "mouse",
    price: 249999,
    stock: 12,
    installments: toInstallments(249999),
    badges: ["mas-vendido"],
    shortDescription: "Peso ultraligero con sensor Focus Pro de 35K DPI.",
    description:
      "Un mouse orientado al máximo rendimiento competitivo, con switches ópticos de tercera generación y polling rate extremo.",
    specs: [
      { label: "Peso", value: "54 g" },
      { label: "Sensor", value: "Focus Pro 35K" },
      { label: "Polling", value: "Hasta 8000 Hz" },
      { label: "Batería", value: "Hasta 95 h" },
    ],
    images: ["Vista superior", "Grip lateral", "Sensor"],
    rating: 4.8,
    reviewCount: 124,
    sold: 396,
    isFeatured: true,
  },
  {
    id: "p3",
    slug: "auricular-hyperx-cloud-iii-wireless",
    name: "Auricular HyperX Cloud III Wireless",
    brand: "HyperX",
    category: "auriculares",
    price: 219999,
    previousPrice: 239999,
    stock: 19,
    installments: toInstallments(219999),
    badges: ["oferta"],
    shortDescription: "Comodidad total y micrófono claro con batería extendida.",
    description:
      "Ideal para largas sesiones de juego, con almohadillas memory foam y audio espacial para ventaja táctica.",
    specs: [
      { label: "Drivers", value: "53 mm" },
      { label: "Autonomía", value: "Hasta 120 h" },
      { label: "Conexión", value: "2.4 GHz" },
      { label: "Compatibilidad", value: "PC / PS5" },
    ],
    images: ["Vista completa", "Micrófono", "Copa interna"],
    rating: 4.7,
    reviewCount: 67,
    sold: 190,
  },
  {
    id: "p4",
    slug: "monitor-asus-rog-strix-xg27aqmr-300hz",
    name: "Monitor Asus ROG Strix XG27AQMR 300Hz",
    brand: "Asus ROG",
    category: "monitores",
    price: 899999,
    previousPrice: 979999,
    stock: 5,
    installments: toInstallments(899999),
    badges: ["destacado", "nuevo"],
    shortDescription: "27 pulgadas QHD IPS con 300Hz para esports premium.",
    description:
      "Panel veloz y colores precisos para competir y crear. Incluye sincronización adaptativa y baja latencia de entrada.",
    specs: [
      { label: "Resolución", value: "2560x1440" },
      { label: "Refresh rate", value: "300 Hz" },
      { label: "Tiempo de respuesta", value: "1 ms" },
      { label: "Panel", value: "Fast IPS" },
    ],
    images: ["Frontal", "Perfil", "Conectores"],
    rating: 4.9,
    reviewCount: 33,
    sold: 74,
    isFeatured: true,
  },
  {
    id: "p5",
    slug: "mousepad-steelseries-qck-prism-xl",
    name: "Mousepad SteelSeries QcK Prism XL",
    brand: "SteelSeries",
    category: "mousepads",
    price: 79999,
    stock: 35,
    installments: toInstallments(79999),
    badges: ["mas-vendido"],
    shortDescription: "Superficie dual y base antideslizante XL.",
    description:
      "Mousepad de alto rendimiento con borde iluminado y doble cara para alternar entre speed y control.",
    specs: [
      { label: "Tamaño", value: "900 x 300 mm" },
      { label: "Superficie", value: "Dual speed/control" },
      { label: "Base", value: "Goma antideslizante" },
      { label: "Borde", value: "RGB" },
    ],
    images: ["Plano completo", "Textura", "Borde"],
    rating: 4.6,
    reviewCount: 58,
    sold: 280,
  },
  {
    id: "p6",
    slug: "teclado-redragon-k617-fizz",
    name: "Teclado Redragon K617 Fizz 60%",
    brand: "Redragon",
    category: "teclados",
    price: 69999,
    previousPrice: 78999,
    stock: 41,
    installments: toInstallments(69999),
    badges: ["oferta"],
    shortDescription: "Compacto 60% con switches mecánicos y RGB.",
    description:
      "Excelente opción calidad/precio para armar setup competitivo sin romper presupuesto.",
    specs: [
      { label: "Formato", value: "60%" },
      { label: "Switch", value: "Redragon Red" },
      { label: "Conexión", value: "USB-C" },
      { label: "Anti-ghosting", value: "Sí" },
    ],
    images: ["Vista superior", "Perfil bajo", "RGB"],
    rating: 4.5,
    reviewCount: 212,
    sold: 612,
  },
  {
    id: "p7",
    slug: "mouse-logitech-g502-x-plus",
    name: "Mouse Logitech G502 X Plus",
    brand: "Logitech",
    category: "mouse",
    price: 199999,
    stock: 16,
    installments: toInstallments(199999),
    badges: ["destacado"],
    shortDescription: "Ergonómico premium con sensores HERO y RGB.",
    description:
      "Control preciso para FPS y MMO, con múltiples botones programables y excelente autonomía.",
    specs: [
      { label: "Sensor", value: "HERO 25K" },
      { label: "Peso", value: "106 g" },
      { label: "Conectividad", value: "LIGHTSPEED + BT" },
      { label: "Botones", value: "13" },
    ],
    images: ["Vista 3/4", "Botones", "Base"],
    rating: 4.8,
    reviewCount: 101,
    sold: 244,
    isFeatured: true,
  },
  {
    id: "p8",
    slug: "monitor-msi-g274qpf-e2-180hz",
    name: "Monitor MSI G274QPF E2 180Hz",
    brand: "MSI",
    category: "monitores",
    price: 529999,
    stock: 7,
    installments: toInstallments(529999),
    badges: ["nuevo"],
    shortDescription: "QHD 27 pulgadas con 180Hz y panel rapid IPS.",
    description:
      "Un equilibrio ideal entre rendimiento competitivo y fidelidad de color para uso mixto gaming/productividad.",
    specs: [
      { label: "Tamaño", value: "27 pulgadas" },
      { label: "Resolución", value: "QHD" },
      { label: "Refresh rate", value: "180 Hz" },
      { label: "Respuesta", value: "1 ms" },
    ],
    images: ["Frontal", "Base", "Puertos"],
    rating: 4.7,
    reviewCount: 41,
    sold: 98,
  },
  {
    id: "p9",
    slug: "webcam-corsair-facecam-mk2",
    name: "Webcam Corsair Facecam MK.2",
    brand: "Corsair",
    category: "accesorios",
    price: 179999,
    stock: 22,
    installments: toInstallments(179999),
    badges: ["destacado"],
    shortDescription: "Streaming 1080p60 con lente premium.",
    description:
      "Imagen clara en baja luz y colorimetría consistente para streamers y reuniones exigentes.",
    specs: [
      { label: "Resolución", value: "1080p a 60 FPS" },
      { label: "Lente", value: "Gran angular" },
      { label: "Conexión", value: "USB-C" },
      { label: "Compatibilidad", value: "PC / Mac" },
    ],
    images: ["Frontal", "Montaje", "Sensor"],
    rating: 4.6,
    reviewCount: 28,
    sold: 66,
  },
  {
    id: "p10",
    slug: "auricular-logitech-g-pro-x-2-lightspeed",
    name: "Auricular Logitech G Pro X 2 Lightspeed",
    brand: "Logitech",
    category: "auriculares",
    price: 319999,
    stock: 11,
    installments: toInstallments(319999),
    badges: ["mas-vendido", "destacado"],
    shortDescription: "Audio competitivo de alta fidelidad con Graphene.",
    description:
      "Pensado para esports profesional, con excelente posicionamiento sonoro y micrófono desmontable.",
    specs: [
      { label: "Drivers", value: "50 mm Graphene" },
      { label: "Batería", value: "Hasta 50 h" },
      { label: "Conexión", value: "2.4 GHz + BT + Cable" },
      { label: "Peso", value: "345 g" },
    ],
    images: ["Frente", "Mic desmontable", "Vincha"],
    rating: 4.9,
    reviewCount: 95,
    sold: 222,
    isFeatured: true,
  },
  {
    id: "p11",
    slug: "mouse-glorious-model-o-2-pro",
    name: "Mouse Glorious Model O 2 Pro",
    brand: "Glorious",
    category: "mouse",
    price: 159999,
    stock: 18,
    installments: toInstallments(159999),
    badges: ["nuevo"],
    shortDescription: "Shape ambidiestro con latencia mínima.",
    description:
      "Pensado para aimers competitivos que necesitan ligereza extrema y tracking estable.",
    specs: [
      { label: "Peso", value: "57 g" },
      { label: "Switch", value: "Ópticos" },
      { label: "Sensor", value: "BAMF 2.0" },
      { label: "Batería", value: "80 h" },
    ],
    images: ["Top", "Lateral", "Base"],
    rating: 4.7,
    reviewCount: 38,
    sold: 84,
  },
  {
    id: "p12",
    slug: "soporte-auriculares-hyperx-chargeplay-base",
    name: "Soporte HyperX ChargePlay Base",
    brand: "HyperX",
    category: "accesorios",
    price: 89999,
    stock: 29,
    installments: toInstallments(89999),
    badges: ["oferta"],
    shortDescription: "Stand premium para auriculares con base de carga.",
    description:
      "Orden y estética para el escritorio con un accesorio sólido y funcional.",
    specs: [
      { label: "Material", value: "Aluminio" },
      { label: "Carga", value: "USB" },
      { label: "Formato", value: "Universal" },
      { label: "Color", value: "Negro mate" },
    ],
    images: ["Frontal", "Detalle base", "Setup"],
    rating: 4.4,
    reviewCount: 21,
    sold: 63,
  },
];

export const faqItems: FAQItem[] = [
  {
    question: "¿Hacen envíos a toda Argentina?",
    answer:
      "Sí, realizamos envíos a todo el país por Correo Argentino, Andreani y OCA con seguimiento en tiempo real.",
  },
  {
    question: "¿Qué medios de pago aceptan?",
    answer:
      "Podés pagar con Mercado Pago, tarjeta de crédito y transferencia bancaria.",
  },
  {
    question: "¿Los productos son originales?",
    answer:
      "Sí. Trabajamos con proveedores confiables y publicamos únicamente productos originales.",
  },
  {
    question: "¿Cómo funcionan cambios y devoluciones?",
    answer:
      "Tenés 10 días para solicitar cambios o devoluciones por falla o disconformidad, según nuestras condiciones de compra.",
  },
  {
    question: "¿Cómo sé si hay stock real?",
    answer:
      "El stock se actualiza en tiempo real en la tienda. Si un producto está disponible, podés comprarlo inmediatamente.",
  },
  {
    question: "¿Cuánto tarda en llegar mi compra?",
    answer:
      "AMBA: 24/48 hs hábiles. Interior del país: entre 2 y 6 días hábiles según destino y operador logístico.",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    name: "Nico P.",
    rating: 5,
    comment: "Una locura la respuesta de teclas. Llegó en 24hs y súper bien embalado.",
    verified: true,
  },
  {
    id: "r2",
    productId: "p1",
    name: "Mica F.",
    rating: 4,
    comment: "Muy premium, ideal para Valorant. El servicio de Norte excelente.",
    verified: true,
  },
  {
    id: "r3",
    productId: "p2",
    name: "Dami S.",
    rating: 5,
    comment: "Liviano y preciso, cambió mi aim al toque.",
    verified: true,
  },
  {
    id: "r4",
    productId: "p10",
    name: "Valen T.",
    rating: 5,
    comment: "Audio impecable para competitivo y música.",
    verified: true,
  },
];

export const benefitItems = [
  {
    title: "Productos originales",
    description: "Catálogo seleccionado con productos originales y publicación transparente.",
  },
  {
    title: "Envíos a todo el país",
    description: "Cobertura nacional con seguimiento y opciones de retiro.",
  },
  {
    title: "Atención personalizada",
    description: "Asesoramiento humano por WhatsApp y soporte postventa real.",
  },
  {
    title: "Mejor precio del país",
    description: "Política de precio competitivo con promociones actualizadas.",
  },
];
